#!/bin/sh

set -e

cd /yaf
sudo mkdir -p /yaf/vendor
sudo chown -R www:www /yaf/vendor

if [ ! -f /yaf/vendor/autoload.php ]; then
    echo "----composer install----"
    sudo -u www composer install --no-interaction
else
    echo "----composer install skipped, reuse existing vendor----"
fi

cd -

sleep 5
echo "----build crontab----"
if ! sudo -u www php /yaf/script/dataddy_cli buildCron; then
    echo "----build crontab failed, continue startup----"
fi
if ! sudo -u www php /yaf/script/dataddy_cli buildCron; then
    echo "----build crontab failed, continue startup----"
fi
# /usr/bin/php /yaf/script/dataddy_cli buildCron

echo "\n"


echo "----start fpm----"
exec php-fpm -F
